---
abstract: 'Parse Cisco-style configuration files'
author:
  - 'David Muir Sharnoff <cpan@dave.sharnoff.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cisco-Reconfig
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: 1.07
resources:
  repository: http://github.com/muir/Cisco-Reconfig
version: 0.901
