--- #YAML:1.0
name:               Cisco-Reconfig
version:            0.9
abstract:           Parse Cisco-style configuration files
author:
    - David Muir Sharnoff <cpan@dave.sharnoff.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Scalar::Util:  1.07
resources:
    repository:  http://github.com/muir/Cisco-Reconfig
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
